"""dropped the Areas table

Revision ID: 5c36c97caa20
Revises: 95156b963e4d
Create Date: 2024-10-22 11:34:27.928962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c36c97caa20'
down_revision = '95156b963e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('Areas')
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=True))
        #batch_op.drop_constraint('Venue_areas_id_fkey', type_='foreignkey')
        #batch_op.drop_column('areas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Venue_areas_id_fkey', 'Areas', ['areas_id'], ['id'])
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    op.create_table('Areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Areas_pkey')
    )
    # ### end Alembic commands ###
